### ISSUE TITLE
npm derrière le proxy

### ISSUE THREAD

**Issue by vallettea** [KrysD/Antsday2#1]
Salut Christophe,

pour demain il faudrait vraiment qu'on arrive à faire tourner npm.
Je met @iOiurson dans la boucle car c'est lui qui va transpirer demain.

Si je me souviens, vendredi soir tu as cloné antcolony et tu as ajouté:

```
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```

au démarrage de conEmu.
Malgré ça, ça timeout.

En fait je crois qu'on a juste copié rapid les lignes qui concernaient git mais en y regardant de plus près j'ai l'impression que ce n'est pas la même synthaxe.
Tu peux vérifier stp.

**Comment by KrysD** [comment]
Salut Alexandre,

Oui c'est exactement ça dans le setting on a mit les mêmes options que pour `docker`.

```
npm config --global https.proxy http://GreenID:mdp@proxy.company:80

npm config --global http.proxy http://GreenID:mdp@proxy.company:80
```

j'ai pas encore testé mais en effet il semble y avoir une différence pour `node.js` ([voir ici](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/))

```
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
```

Ils mettent `config set` et nous comme `docker` `config --global` je sais pas si ça influe ou non sur le résultat.  
je met un link des messages d'erreur timeout

```
npm WARN package.json AntColony@0.1.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 185.31.17.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ZQ5239\Documents\Formation Ants\clone\AntColony\npm-debug.log
```

## Edit 1

J'ai appliqué les changements par rapport à ce que j'ai vue sur le net et j'ai la même erreur

## Edit 2

j'ai ajouté le fichier `npm-debug` qui a été créé suite à l'erreur au repository.

**Comment by KrysD** [comment]
je met un link des messages d'erreur timeout

```
npm WARN package.json AntColony@0.1.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 185.31.17.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ZQ5239\Documents\Formation Ants\clone\AntColony\npm-debug.log
```

**Comment by vallettea** [comment]
c'est que les paramètres du proxy sont pas bien set.

regarde ce que rend la commande:

```
npm config ls -l
```

si les variables de proxy n'y sont pas revérifie ce qu'on a mis dans conemu et si c'est bon essaie de mettre ces paramètre dans `/tonHome/.npmrc` comme suggéré [ici](https://docs.npmjs.com/misc/config).

merci

**Comment by KrysD** [comment]
Voilà ce que j'ai avec la commande : 

```
nmp config ls -l
```

Je regarde en même le lien pour les paramètres.

```
; cli configs
long = true
user-agent = "npm/2.14.12 node/v4.2.4 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\ZQ5239\\AppData\\Roaming\\npm"

; default values
access = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\ZQ5239\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "C:\\Users\\ZQ5239\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\ZQ5239\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\ZQ5239\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "4.2.4"
npat = false
onload-script = null
optional = true
parseable = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\\Windows\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
spin = true
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "C:\\Users\\ZQ5239\\AppData\\Local\\Temp"
umask = 0
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\ZQ5239\\.npmrc"
version = false
versions = false
viewer = "browser"
```

**Comment by vallettea** [comment]
ouais le proxy est null. au moins ça sert à rien d'attendre une plombe que ça timeout pour debuguer. tant que cette variable n'est pas set, ça marchera pas.

**Comment by KrysD** [comment]
Ok c'est rassurant on est déjà certain d'où ca vient. 

J'ai regarder pour quels utilisateurs du pc les config étaient crées :

```
npm config ls -l | grep config
```

il m'indique que j'ai un fichier .npmrc de crée pour l'utilisateur (qui a une priorité plus forte que la global config) mais pourant je n'ai rien à l'emplacement indiqué. 

```
; cli configs
; builtin config undefined
globalconfig = "C:\\Users\\ZQ5239\\AppData\\Roaming\\npm\\etc\\npmrc"
userconfig = "C:\\Users\\ZQ5239\\.npmrc"
```

je vais voir si ça marche si j'ajoute quand même le fichier avec les config du proxy à la main au même repository que `userconfig`

**Comment by KrysD** [comment]
Juste avant j'ai essayé de mettre les commandes de config directement dans conEmu pour tester le `npm install`, voilà ce que j'ai :

```
npm WARN package.json AntColony@0.1.0 No repository field.
parse-svg-path@0.1.1 node_modules\parse-svg-path

delaunay-triangulate@1.1.6 node_modules\delaunay-triangulate
├── uniq@1.0.1
└── incremental-convex-hull@1.0.1 (simplicial-complex@1.0.0, robust-orientation@1.1.3)
```

j'ai plusieurs nouveau fichier dans le repository maintenant

**Comment by KrysD** [comment]
Alors ca semble fonctionner maintenant, voilà comment j'ai fait pour créer le fichier .npmrc
1. Lancer conEmu
2. taper la commande : `npm config set prefix "${APPDATA}/npm" -g`
3. taper la commande : `npm config get prefix -g`
4. Inserer les commandes de proxy : 
   -  `npm config set proxy http://greenID:mdp@proxy_company:8080`
   - `npm config set https-proxy http://greenID:mdp@proxy_company:8080`
5. lancer la commande : `npm install`

J'ai par la suite un fichier `.nprmc` de crée dans le userConfig repository avec les config proxy dedans

```
proxy=http://greenID:mdp@proxy_company:8080/
https-proxy=http://greenID:mdp@proxy_company:8080
```

**Comment by vallettea** [comment]
:clap: tu gères meci beaucoup
@iOiurson a noter pour demain
